### PR TITLE
Accept and pass emulator options in run.sh

### PR DESCRIPTION
**Pull request by iki**
We need to pass debug options like `--log-http --verbosity=debug --user-output-enabled`.

### CODE REVIEW

**Comment by marcelcorso** [comment]
Hey @iki thanks for the PR. It's a good idea. 

Can you please add docs for this on the README?

**Comment by rogierlommers** [comment]
Hey @iki , can you please do that? Would love to be able to set debug level and log in human-friendly notation.

**Comment by iki** [comment]
Sure, I'll be back from traveling in a week and will add the docs.

**Comment by hannesdejager** [comment]
+1, would be great to have. Thanks!

**Comment by marcelcorso** [comment]
@rogierlommers @hannesdejager I didn't had time to test the PR. If you guys tell me it works I merge, push and then Iki can do the docs on another PR. Maybe that can speed up things.

**Comment by rogierlommers** [comment]
Yes please do so, works fine.

**Comment by marcelcorso** [comment]
pushed ✅

**Pull request merged**
